#############################################################################
# Generated by PAGE version 5.0.2
#  in conjunction with Tcl version 8.6
#  Mar 19, 2020 11:52:26 AM EDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #ffffff
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #ffffff
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ffffff
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #ffffff
set vTcl(pr,menuanalogcolor) #ffffff
set vTcl(pr,treehighlight) #ff0000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background #c0c0c0 -highlightbackground #00ff40 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x480
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Main"
    vTcl:DefineAlias "$top" "Main" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 10 -background #c0c0c0 -height 480 \
        -highlightbackground #000000 -highlightcolor #ff0080 -width 267 
    vTcl:DefineAlias "$top.fra45" "LEFT_SIDE" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.fra45
    button $site_3_0.but46 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #00ff00 -borderwidth 10 -command COMMAND_START_POUR \
        -compound center -cursor arrow -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Light} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #000000 \
        -pady 0 -text POUR 
    vTcl:DefineAlias "$site_3_0.but46" "Button_POUR" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.but46
    button $site_3_0.but54 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ff0000 -borderwidth 10 -command COMMAND_STOP_POUR \
        -compound center -cursor fleur -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Light} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text E-STOP 
    vTcl:DefineAlias "$site_3_0.but54" "Button_ESTOP" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.but54
    button $site_3_0.but44 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #0080ff -borderwidth 10 -command COMMAND_CLEAN \
        -compound center -cursor fleur -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Light} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text CLEAN 
    vTcl:DefineAlias "$site_3_0.but44" "Button_CLEAN" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.but44
    place $site_3_0.but46 \
        -in $site_3_0 -x 0 -relx 0.337 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.468 -height 0 -relheight 0.208 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.337 -y 0 -rely 0.417 -width 0 \
        -relwidth 0.468 -height 0 -relheight 0.208 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but44 \
        -in $site_3_0 -x 0 -relx 0.337 -y 0 -rely 0.677 -width 0 \
        -relwidth 0.468 -height 0 -relheight 0.208 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.fra45
    frame $top.fra46 \
        -borderwidth 10 -background #c0c0c0 -height 480 \
        -highlightbackground #000000 -highlightcolor #ff0080 -width 253 
    vTcl:DefineAlias "$top.fra46" "MIDDLE" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 16} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {HERR FAUSS} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label_HERR_FAUSS" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab47
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Drink Responsibly} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label_Drink_Responsibly" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab49
    spinbox $site_3_0.spi52 \
        -activebackground #f9f9f9 -background white -buttonbackground #ffffff \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 12} \
        -foreground black -from 1.0 -highlightbackground #0000ff \
        -highlightcolor #0000ff -increment 1.0 -insertbackground black \
        -justify center -selectbackground #c4c4c4 -selectforeground black \
        -textvariable spinbox -to 100.0 -values {4 8 16} 
    vTcl:DefineAlias "$site_3_0.spi52" "Spinbox_Beer_Size" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.spi52
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Select Beer Size (oz)} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label_Drink_Responsibly_8" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab53
    place $site_3_0.lab47 \
        -in $site_3_0 -x 45 -y 0 -rely 0.125 -width 150 -relwidth 0 -height 0 \
        -relheight 0.054 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.168 -y 0 -rely 0.219 -width 155 \
        -relwidth 0 -height 0 -relheight 0.054 -anchor nw -bordermode ignore 
    place $site_3_0.spi52 \
        -in $site_3_0 -x 60 -y 240 -width 131 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 15 -y 200 -width 220 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra46
    frame $top.fra44 \
        -borderwidth 10 -background #c0c0c0 -height 480 \
        -highlightbackground #000000 -highlightcolor #ff0080 -width 400 
    vTcl:DefineAlias "$top.fra44" "RIGHT_SIDE" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.fra44
    button $site_3_0.but44 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #808080 -borderwidth 1 -command COMMAND_RESET_KEG_LEVEL \
        -compound center -cursor fleur -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Light} -size 12} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #000000 \
        -pady 0 -text {Keg Level} 
    vTcl:DefineAlias "$site_3_0.but44" "Button_Reset_Keg_Level" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.but44
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text Information 
    vTcl:DefineAlias "$site_3_0.lab45" "Label_Information" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab45
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Keg Level} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label_Keg_Level" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab46
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black -justify left \
        -text {0 %} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label_Value_Keg_Level" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab48
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {CO2 (psi)} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label_CO2" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab50
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black -justify left \
        -text 0 
    vTcl:DefineAlias "$site_3_0.lab51" "Label_Value_CO2" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab51
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text Analytics 
    vTcl:DefineAlias "$site_3_0.lab52" "Label_Analytics" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab52
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Cumulative (oz)} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label_Cumulative" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab53
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black -justify left \
        -text 0 
    vTcl:DefineAlias "$site_3_0.lab54" "Label_Value_Cumulative" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab54
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text Reset 
    vTcl:DefineAlias "$site_3_0.lab55" "Label_Reset" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.lab55
    button $site_3_0.but56 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #808080 -borderwidth 1 -command COMMAND_RESET_CUMULATIVE \
        -compound center -cursor fleur -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Light} -size 12} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #000000 \
        -pady 0 -text Cumulative 
    vTcl:DefineAlias "$site_3_0.but56" "Button_Reset_Cumulative" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $site_3_0.but56
    place $site_3_0.but44 \
        -in $site_3_0 -x 75 -y 370 -width 125 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 60 -y 105 -width 160 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -y 140 -width 160 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 150 -y 140 -width 85 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -y 185 -width 160 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 150 -y 185 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 60 -y 240 -width 160 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -y 285 -width 160 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 150 -y 285 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 60 -y 330 -width 160 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 75 -y 420 -width 125 -height 40 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.fra44
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black -background #ff0000 \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text Error(s): 
    vTcl:DefineAlias "$top.lab59" "Label_Error_Bar" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $top.lab59
    label $top.lab60 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #dbdbdb -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black -justify left \
        -text None 
    vTcl:DefineAlias "$top.lab60" "Label_Value_Error" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $top.lab60
    label $top.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #000000 \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 12} \
        -foreground #ffffff -highlightbackground #d9d9d9 \
        -highlightcolor black -text Status: 
    vTcl:DefineAlias "$top.lab61" "Label_Status_Bar" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $top.lab61
    label $top.lab62 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #dbdbdb -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black -justify left \
        -text Ready 
    vTcl:DefineAlias "$top.lab62" "Label_Value_Status" vTcl:WidgetProc "Main" 1
    vTcl:copy_lock $top.lab62
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -y 0 -width 267 -relwidth 0 -height 480 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 270 -y 0 -width 253 -relwidth 0 -height 480 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 525 -y 0 -width 267 -height 480 -anchor nw \
        -bordermode ignore 
    place $top.lab59 \
        -in $top -x 255 -y 425 -width 125 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 380 -y 425 -width 155 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 255 -y 370 -width 125 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 380 -y 370 -width 155 -height 45 -anchor nw \
        -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

